name: Build Docs

on:
  pull_request:
  push:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # to match .readthedocs.yaml
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[doc]

      - name: Build HTML docs
        run: |
          cd docs
          make html
